const wardrobe={hair:['Silver curtains','Midnight tousle','Ash crop','Brown curtains','Long black layers','Blond slick-back'],tops:['Rebel uniform','Varsity jacket','Olive bomber','Cream cardigan','Biker leather','Track jacket'],bottoms:['Uniform trousers','Blue denim','Cargo trousers','Pleated chinos','Ripped denim','Track pants'],shoes:['School boots','White sneakers','Combat boots','Penny loafers','Red high-tops','Sport trainers'],accessories:['No extras','Silver chain','Face bandages','Dark shades','School pin','Chain + bandages']};
const styleNames=['School rebel','Varsity club','Street crew','Soft academia','Midnight rider','Track team'];
const categoryNames={hair:'Hairstyles',tops:'Tops',bottoms:'Bottoms',shoes:'Shoes',accessories:'Accessories'};
const paths={hair:'M4 15V8l4-5h8l4 5v7l-4-5-4-3-4 5v3M4 15v5h4M20 15v5h-4',tops:'M8 3L2 7l3 6 3-2v10h8V11l3 2 3-6-6-4-4 3z',bottoms:'M6 3h12l2 18h-7l-1-11-1 11H4zM6 7h12',shoes:'M4 5h7v7l9 4v5H3V10zM3 17h17',accessories:'M3 5v7l4 7h10l4-7V5M7 4v8l5 5 5-5V4'};
let selected={hair:0,tops:0,bottoms:0,shoes:0,accessories:5},active='hair',ready=false,sprites=[];
// Each generated doll is aligned to a common 128 x 256 rig; exchangeable regions use the same boundary lines.
const regions={hair:[0,85],tops:[85,168],bottoms:[168,217],shoes:[217,256]};
const doll=document.querySelector('#doll'),ctx=doll.getContext('2d');
function accessory(c,id,scale=1){c.save();c.scale(scale,scale);const box=(x,y,w,h,color)=>{c.fillStyle=color;c.fillRect(x,y,w,h)};
 if(id===1||id===5){[[51,89],[53,93],[55,97],[58,100],[62,103],[66,103],[70,100],[73,97],[75,93]].forEach(([x,y])=>{box(x,y,3,2,'#474945');box(x,y,2,1,'#e4e5d4')});box(63,105,3,5,'#ddddc9')}
 if(id===2||id===5){box(72,43,7,10,'#e8d8b4');box(74,46,3,4,'#a35f51');box(57,63,11,3,'#e7cab4');box(62,63,2,3,'#aa6156')}
 if(id===3){box(44,62,17,9,'#171c1d');box(67,62,17,9,'#171c1d');box(59,64,10,3,'#171c1d');box(46,63,5,2,'#65747c');box(69,63,5,2,'#65747c')}
 if(id===4){box(77,100,8,11,'#29302b');box(78,101,6,9,'#d5b863');box(80,103,2,5,'#434c35')}
 c.restore();}
function renderDoll(){if(!ready)return;ctx.clearRect(0,0,256,512);ctx.imageSmoothingEnabled=false;ctx.drawImage(sprites[selected.bottoms],0,142,128,75,0,284,256,150);ctx.drawImage(sprites[selected.shoes],0,217,128,39,0,434,256,78);const top=document.createElement('canvas');top.width=128;top.height=256;const t=top.getContext('2d');t.drawImage(sprites[selected.tops],0,85,128,85,0,85,128,85);t.clearRect(51,142,26,28);t.clearRect(40,158,48,12);ctx.drawImage(top,0,0,256,512);ctx.drawImage(sprites[selected.hair],0,0,128,85,0,0,256,170);accessory(ctx,selected.accessories,2);doll.setAttribute('aria-label','Cho Seongil: '+Object.keys(selected).map(k=>wardrobe[k][selected[k]]).join(', '));}
function renderItems(){const holder=document.querySelector('#items');holder.replaceChildren();document.querySelector('#category-title').textContent=categoryNames[active];wardrobe[active].forEach((name,i)=>{const b=document.createElement('button');b.className='item'+(selected[active]===i?' selected':'');b.setAttribute('aria-label','Wear '+name);b.setAttribute('aria-pressed',String(selected[active]===i));b.innerHTML='<span class="item-preview"><canvas width="128" height="100" aria-hidden="true"></canvas></span><span class="item-caption"><span>'+name+'</span><span class="item-number">0'+(i+1)+'</span></span>'+(selected[active]===i?'<span class="checkmark">✓</span>':'');b.onclick=()=>{selected[active]=i;update('Trying on '+name+'.')};holder.append(b);const c=b.querySelector('canvas').getContext('2d');c.imageSmoothingEnabled=false;if(active==='accessories'){if(i===0){c.strokeStyle='#7d8968';c.lineWidth=2;c.strokeRect(48,32,32,32);c.beginPath();c.moveTo(49,63);c.lineTo(79,33);c.stroke()}else{c.save();c.translate(-40,i===1||i===4?-131:i===5?-70:-53);c.scale(1.65,1.65);accessory(c,i);c.restore()}}else if(ready){const [y,end]=regions[active],h=end-y;const factor=Math.min(96/128,88/h);c.drawImage(sprites[i],0,y,128,h,(128-128*factor)/2,(100-h*factor)/2,128*factor,h*factor)}});document.querySelector('#selected-label').textContent=wardrobe[active][selected[active]];}
function update(message){renderDoll();renderItems();const matched=styleNames.findIndex((_,i)=>['hair','tops','bottoms','shoes'].every(k=>selected[k]===i));document.querySelector('#style-name').textContent=matched<0?'Own rules':styleNames[matched];document.querySelectorAll('.preset').forEach((b,i)=>{b.classList.toggle('active',i===matched);b.setAttribute('aria-pressed',String(i===matched))});if(message)document.querySelector('#status').textContent=message;}
function chooseCategory(key){active=key;document.querySelectorAll('.category').forEach(b=>{b.classList.toggle('active',b.dataset.key===key);b.setAttribute('aria-pressed',String(b.dataset.key===key))});renderItems()}
styleNames.forEach((name,i)=>{const b=document.createElement('button');b.className='preset';b.innerHTML='<span class="num">0'+(i+1)+'</span><span>'+name+'</span><span class="arrow">↗</span>';b.onclick=()=>{['hair','tops','bottoms','shoes'].forEach(k=>selected[k]=i);selected.accessories=i===0?5:i===4?3:i===3?0:1;update(name+' equipped.')};document.querySelector('#presets').append(b)});
Object.keys(wardrobe).forEach(key=>{const b=document.createElement('button');b.className='category';b.dataset.key=key;b.innerHTML='<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="'+paths[key]+'"/></svg><span>'+({hair:'Hair',accessories:'Extras'}[key]||categoryNames[key])+'</span>';b.onclick=()=>chooseCategory(key);document.querySelector('.categories').append(b)});
document.querySelector('#random').onclick=()=>{Object.keys(selected).forEach(k=>selected[k]=Math.floor(Math.random()*wardrobe[k].length));update('New look. Same attitude.')};
document.querySelector('#reset').onclick=()=>{selected={hair:0,tops:0,bottoms:0,shoes:0,accessories:5};update('Back to the original school rebel.')};
async function init(){try{sprites=await Promise.all(Array.from({length:6},(_,i)=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src='assets/doll-'+i+'.png'})));ready=true;document.querySelector('#loading').hidden=true;update()}catch{document.querySelector('#loading').textContent='Could not load the wardrobe. Please refresh.';document.querySelector('#status').textContent='Character artwork could not load.'}}
chooseCategory('hair');update();init();
const scenes={grid:{name:'Fit check',file:null},classroom:{name:'Classroom',file:'assets/classroom.png'},practice:{name:'Practice Room',file:'assets/practice-room.png'}};
let currentScene='grid',sceneRequest=0;
const stage=document.querySelector('.stage'),sceneControls=document.createElement('div');
sceneControls.className='scene-controls';sceneControls.innerHTML='<span class="eyebrow" id="scene-label">LOCATION</span><div class="scene-options" role="group" aria-labelledby="scene-label"></div>';
stage.after(sceneControls);
for(const [key,scene] of Object.entries(scenes)){const b=document.createElement('button');b.className='scene-button';b.dataset.scene=key;b.textContent=scene.name;b.setAttribute('aria-pressed',String(key===currentScene));b.onclick=()=>switchScene(key).catch(()=>{});sceneControls.querySelector('.scene-options').append(b)}
async function switchScene(key){if(!Object.hasOwn(scenes,key))throw new Error('Choose grid, classroom, or practice.');const request=++sceneRequest,scene=scenes[key];let background;
 if(scene.file){document.querySelector('#status').textContent='Opening '+scene.name+'…';try{background=await new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Background could not load. Please try again.'));im.src=scene.file})}catch(error){if(request===sceneRequest)document.querySelector('#status').textContent=error.message;throw error}}
 if(request!==sceneRequest)return{cancelled:true};stage.querySelector('.scene-image')?.remove();if(background){background.className='scene-image';background.alt='';background.setAttribute('aria-hidden','true');stage.prepend(background)}currentScene=key;stage.classList.toggle('has-scene',!!background);stage.dataset.scene=key;stage.setAttribute('aria-label',scene.name+' character backdrop');document.querySelector('.stage-tag').textContent=scene.name.toUpperCase();document.querySelectorAll('.scene-button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===key)));document.querySelector('#status').textContent=scene.name+' · Outfit kept.';return{scene:key,outfitKept:true};}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'switch_scene',description:'Switch the character backdrop without changing the outfit.',inputSchema:{type:'object',properties:{scene:{type:'string',enum:Object.keys(scenes)}},required:['scene'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='scene'))throw new Error('Supply only a scene.');return switchScene(input.scene)}})).catch(()=>{})}catch{}}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_outfit',description:'Equip Cho Seongil with chosen wardrobe item indices (0–5) and update the preview.',inputSchema:{type:'object',properties:Object.fromEntries(Object.keys(wardrobe).map(k=>[k,{type:'integer',minimum:0,maximum:5}])),additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.entries(input).some(([k,v])=>!(k in wardrobe)||!Number.isInteger(v)||v<0||v>5))throw new Error('Use wardrobe categories and item indices from 0 to 5.');selected={...selected,...input};update('Outfit updated.');return{outfit:Object.fromEntries(Object.keys(selected).map(k=>[k,wardrobe[k][selected[k]]]))}}})).catch(()=>{})}catch{}}
